import { Injectable, signal } from '@angular/core';
import { RecipeInfo } from '@shared/models/recipe.model';

@Injectable({
  providedIn: 'root',
})
export class RecipeService {
  recipes = signal<RecipeInfo[]>(MOCK_RECIPES);
}

export const MOCK_RECIPES: RecipeInfo[] = [
  {
    id: 716429,
    title: 'Pasta con salsa de tomate y albahaca',
    image: 'https://spoonacular.com/recipeImages/716429-556x370.jpg',
    imageType: 'jpg',
    readyInMinutes: 30,
    servings: 2,
    sourceUrl: 'https://spoonacular.com/recipes/pasta-with-tomato-sauce-716429',
    spoonacularSourceUrl:
      'https://spoonacular.com/recipes/pasta-with-tomato-sauce-716429',
    summary:
      'Una pasta simple y deliciosa con salsa de tomate natural y albahaca fresca.',
    instructions: 'Cocinar la pasta. Preparar la salsa. Mezclar y servir.',
    analyzedInstructions: [
      {
        name: '',
        steps: [
          {
            number: 1,
            step: 'Hervir agua con sal y cocinar la pasta hasta que esté al dente.',
            ingredients: [],
            equipment: [],
          },
          {
            number: 2,
            step: 'Saltear ajo, agregar tomate triturado y cocinar 10 minutos.',
            ingredients: [],
            equipment: [],
          },
          {
            number: 3,
            step: 'Mezclar la pasta con la salsa y agregar albahaca fresca.',
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    extendedIngredients: [
      {
        id: 20420,
        aisle: 'Pasta and Rice',
        image: 'spaghetti.jpg',
        consistency: 'solid',
        name: 'spaghetti',
        nameClean: 'spaghetti',
        original: '200 g de spaghetti',
        originalName: 'spaghetti',
        amount: 200,
        unit: 'g',
        meta: [],
        measures: {
          us: { amount: 7, unitShort: 'oz', unitLong: 'ounces' },
          metric: { amount: 200, unitShort: 'g', unitLong: 'grams' },
        },
      },
    ],
    cuisines: ['Italian'],
    dishTypes: ['main course'],
    diets: ['vegetarian'],
    occasions: [],
    vegetarian: true,
    vegan: false,
    glutenFree: false,
    dairyFree: true,
    veryHealthy: false,
    cheap: true,
    veryPopular: true,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 12,
    gaps: 'no',
    preparationMinutes: 10,
    cookingMinutes: 20,
    aggregateLikes: 320,
    healthScore: 65,
    creditsText: 'Fake Spoonacular',
    sourceName: 'Spoonacular',
    pricePerServing: 150,
    winePairing: {
      pairedWines: ['chianti'],
      pairingText: 'Combina bien con un vino tinto liviano.',
      productMatches: [],
    },
    complete: true,
    author: 'Spoonacular',
    originalId: null,
  },

  {
    id: 715538,
    title: 'Hamburguesa clásica con queso',
    image: 'https://spoonacular.com/recipeImages/715538-556x370.jpg',
    imageType: 'jpg',
    readyInMinutes: 25,
    servings: 1,
    sourceUrl: '',
    spoonacularSourceUrl: '',
    summary: 'Hamburguesa jugosa con queso cheddar y pan tostado.',
    instructions: 'Cocinar la carne. Armar la hamburguesa.',
    analyzedInstructions: [],
    extendedIngredients: [],
    cuisines: ['American'],
    dishTypes: ['main course'],
    diets: [],
    occasions: [],
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: true,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 18,
    gaps: 'no',
    preparationMinutes: 5,
    cookingMinutes: 20,
    aggregateLikes: 580,
    healthScore: 40,
    creditsText: 'Fake Spoonacular',
    sourceName: 'Spoonacular',
    pricePerServing: 300,
    winePairing: {
      pairedWines: [],
      pairingText: '',
      productMatches: [],
    },
    complete: true,
    author: 'Spoonacular',
    originalId: null,
  },

  {
    id: 782585,
    title: 'Ensalada fresca de quinoa',
    image: 'https://spoonacular.com/recipeImages/782585-556x370.jpg',
    imageType: 'jpg',
    readyInMinutes: 20,
    servings: 2,
    sourceUrl: '',
    spoonacularSourceUrl: '',
    summary: 'Ensalada liviana y nutritiva con quinoa y vegetales.',
    instructions: 'Cocinar la quinoa y mezclar con vegetales.',
    analyzedInstructions: [],
    extendedIngredients: [],
    cuisines: ['Mediterranean'],
    dishTypes: ['salad'],
    diets: ['vegan', 'gluten free'],
    occasions: [],
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: true,
    lowFodmap: false,
    weightWatcherSmartPoints: 6,
    gaps: 'no',
    preparationMinutes: 10,
    cookingMinutes: 10,
    aggregateLikes: 210,
    healthScore: 85,
    creditsText: 'Fake Spoonacular',
    sourceName: 'Spoonacular',
    pricePerServing: 200,
    winePairing: {
      pairedWines: [],
      pairingText: '',
      productMatches: [],
    },
    complete: true,
    author: 'Spoonacular',
    originalId: null,
  },
];
